### PR TITLE
Fix indentation in Documenter workflow

### PR DESCRIPTION
**Pull request by timholy**
This is the maintenance demo

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
YAML indentation - gets me every time.

**Comment by timholy** [comment]
Especially when vscode has a habit of adjusting indentation!

**Comment by timholy** [comment]
Should we advertise this script on discourse? It's close to the deadline, I would have assumed most people had migrated...until I checked this morning for a couple of the orgs I participate in.

**Comment by DilumAluthge** [comment]
> Should we advertise this script on discourse? It's close to the deadline, I would have assumed most people had migrated...until I checked this morning for a couple of the orgs I participate in.

Absolutely!

**Comment by timholy** [comment]
Done: https://discourse.julialang.org/t/easy-workflow-file-for-setting-up-github-actions-ci-for-your-julia-package/49765/55?u=tim.holy

**Pull request merged**
